import type { Team } from './index';
import {
    audiLogo,
    ferrariLogo,
    haasLogo,
    mclarenLogo,
    mercedesLogo,
    redbullracingLogo,
    racingbullsLogo,
    williamsLogo,
    alpineLogo,
    astonMartinLogo,
} from '@shared/assets/images/teams';

export const TEAMS: Team[] = [
    {
        id: 'mclaren',
        name: 'McLaren',
        country: 'GB',
        color: '#FF8700',
        logo: mclarenLogo,
        stats: { pace: 97, reliability: 92, downforce: 85, topSpeed: 88, tyreUsage: 82, pitCrewSpeed: 94, ersEfficiency: 90 },
    },
    {
        id: 'ferrari',
        name: 'Ferrari',
        country: 'IT',
        color: '#DC0000',
        logo: ferrariLogo,
        stats: { pace: 95, reliability: 84, downforce: 88, topSpeed: 86, tyreUsage: 78, pitCrewSpeed: 90, ersEfficiency: 87 },
    },
    {
        id: 'red-bull',
        name: 'Red Bull Racing',
        country: 'AT',
        color: '#1E41FF',
        logo: redbullracingLogo,
        stats: { pace: 96, reliability: 88, downforce: 90, topSpeed: 87, tyreUsage: 80, pitCrewSpeed: 96, ersEfficiency: 92 },
    },
    {
        id: 'mercedes',
        name: 'Mercedes',
        country: 'DE',
        color: '#00D2BE',
        logo: mercedesLogo,
        stats: { pace: 93, reliability: 90, downforce: 83, topSpeed: 92, tyreUsage: 76, pitCrewSpeed: 91, ersEfficiency: 95 },
    },
    {
        id: 'aston-martin',
        name: 'Aston Martin',
        country: 'GB',
        color: '#006F62',
        logo: astonMartinLogo,
        stats: { pace: 88, reliability: 85, downforce: 82, topSpeed: 84, tyreUsage: 74, pitCrewSpeed: 85, ersEfficiency: 82 },
    },
    {
        id: 'alpine',
        name: 'Alpine',
        country: 'FR',
        color: '#0090FF',
        logo: alpineLogo,
        stats: { pace: 85, reliability: 82, downforce: 80, topSpeed: 86, tyreUsage: 72, pitCrewSpeed: 83, ersEfficiency: 80 },
    },
    {
        id: 'williams',
        name: 'Williams',
        country: 'GB',
        color: '#00A3E0',
        logo: williamsLogo,
        stats: { pace: 83, reliability: 80, downforce: 78, topSpeed: 85, tyreUsage: 70, pitCrewSpeed: 81, ersEfficiency: 78 },
    },
    {
        id: 'rb',
        name: 'RB',
        country: 'IT',
        color: '#6692FF',
        logo: racingbullsLogo,
        stats: { pace: 82, reliability: 81, downforce: 79, topSpeed: 84, tyreUsage: 71, pitCrewSpeed: 82, ersEfficiency: 79 },
    },
    {
        id: 'audi',
        name: 'Audi',
        country: 'DE',
        color: '#52E07C',
        logo: audiLogo,
        stats: { pace: 78, reliability: 76, downforce: 75, topSpeed: 82, tyreUsage: 68, pitCrewSpeed: 78, ersEfficiency: 77 },
    },
    {
        id: 'haas',
        name: 'Haas',
        country: 'US',
        color: '#B6B6B6',
        logo: haasLogo,
        stats: { pace: 76, reliability: 74, downforce: 73, topSpeed: 80, tyreUsage: 66, pitCrewSpeed: 76, ersEfficiency: 74 },
    },
];
