import type { Team } from './index';
import {
    audiLogo,
    ferrariLogo,
    haasLogo,
    mclarenLogo,
    mercedesLogo,
    redbullracingLogo,
    racingbullsLogo,
    williamsLogo,
    alpineLogo,
    astonMartinLogo,
    cadillacLogo,
} from '@shared/assets/images/teams';

export const TEAMS: Team[] = [
    {
        id: 'mercedes',
        name: 'Mercedes',
        country: 'DE',
        color: '#00D2BE',
        logo: mercedesLogo,
        stats: { pace: 90, reliability: 88, downforce: 84, topSpeed: 87, tyreUsage: 85, pitCrewSpeed: 91, ersEfficiency: 91 },
    },
    {
        id: 'ferrari',
        name: 'Ferrari',
        country: 'IT',
        color: '#DC0000',
        logo: ferrariLogo,
        stats: { pace: 90, reliability: 83, downforce: 82, topSpeed: 89, tyreUsage: 85, pitCrewSpeed: 90, ersEfficiency: 87 },
    },
    {
        id: 'mclaren',
        name: 'McLaren',
        country: 'GB',
        color: '#FF8700',
        logo: mclarenLogo,
        stats: { pace: 88, reliability: 90, downforce: 86, topSpeed: 83, tyreUsage: 84, pitCrewSpeed: 88, ersEfficiency: 87 },
    },
    {
        id: 'red-bull',
        name: 'Red Bull Racing',
        country: 'AT',
        color: '#1E41FF',
        logo: redbullracingLogo,
        stats: { pace: 84, reliability: 90, downforce: 93, topSpeed: 87, tyreUsage: 83, pitCrewSpeed: 91, ersEfficiency: 84 },
    },
    {
        id: 'rb',
        name: 'RB',
        country: 'IT',
        color: '#6692FF',
        logo: racingbullsLogo,
        stats: { pace: 82, reliability: 84, downforce: 79, topSpeed: 84, tyreUsage: 77, pitCrewSpeed: 84, ersEfficiency: 78 },
    },
    {
        id: 'alpine',
        name: 'Alpine',
        country: 'FR',
        color: '#0090FF',
        logo: alpineLogo,
        stats: { pace: 85, reliability: 81, downforce: 78, topSpeed: 85, tyreUsage: 77, pitCrewSpeed: 83, ersEfficiency: 77 },
    },
    {
        id: 'haas',
        name: 'Haas',
        country: 'US',
        color: '#B6B6B6',
        logo: haasLogo,
        stats: { pace: 83, reliability: 74, downforce: 73, topSpeed: 86, tyreUsage: 71, pitCrewSpeed: 76, ersEfficiency: 74 },
    },
    {
        id: 'audi',
        name: 'Audi',
        country: 'DE',
        color: '#F50537',
        logo: audiLogo,
        stats: { pace: 81, reliability: 77, downforce: 75, topSpeed: 82, tyreUsage: 73, pitCrewSpeed: 78, ersEfficiency: 77 },
    },
    {
        id: 'williams',
        name: 'Williams',
        country: 'GB',
        color: '#00A3E0',
        logo: williamsLogo,
        stats: { pace: 79, reliability: 78, downforce: 75, topSpeed: 83, tyreUsage: 73, pitCrewSpeed: 81, ersEfficiency: 78 },
    },
    {
        id: 'aston-martin',
        name: 'Aston Martin',
        country: 'GB',
        color: '#006F62',
        logo: astonMartinLogo,
        stats: { pace: 68, reliability: 80, downforce: 77, topSpeed: 74, tyreUsage: 76, pitCrewSpeed: 85, ersEfficiency: 80 },
    },
    {
        id: 'cadillac',
        name: 'Cadillac',
        country: 'US',
        color: '#005BAC',
        logo: cadillacLogo,
        stats: { pace: 70, reliability: 78, downforce: 75, topSpeed: 79, tyreUsage: 65, pitCrewSpeed: 72, ersEfficiency: 68 },
    }
];


// import type { Team } from './index';
// import {
//     audiLogo,
//     ferrariLogo,
//     haasLogo,
//     mclarenLogo,
//     mercedesLogo,
//     redbullracingLogo,
//     racingbullsLogo,
//     williamsLogo,
//     alpineLogo,
//     astonMartinLogo,
//     cadillacLogo,
// } from '@shared/assets/images/teams';

// export const TEAMS: Team[] = [
//     {
//         id: 'mercedes',
//         name: 'Mercedes',
//         country: 'DE',
//         color: '#00D2BE',
//         logo: mercedesLogo,
//         stats: { pace: 70, reliability: 70, downforce: 70, topSpeed: 70, tyreUsage: 70, pitCrewSpeed: 70, ersEfficiency: 70 },
//     },
//     {
//         id: 'ferrari',
//         name: 'Ferrari',
//         country: 'IT',
//         color: '#DC0000',
//         logo: ferrariLogo,
//         stats: { pace: 70, reliability: 70, downforce: 70, topSpeed: 70, tyreUsage: 70, pitCrewSpeed: 70, ersEfficiency: 70 },
//     },
//     {
//         id: 'mclaren',
//         name: 'McLaren',
//         country: 'GB',
//         color: '#FF8700',
//         logo: mclarenLogo,
//         stats: { pace: 70, reliability: 70, downforce: 70, topSpeed: 70, tyreUsage: 70, pitCrewSpeed: 70, ersEfficiency: 70 },
//     },
//     {
//         id: 'red-bull',
//         name: 'Red Bull Racing',
//         country: 'AT',
//         color: '#1E41FF',
//         logo: redbullracingLogo,
//         stats: { pace: 70, reliability: 70, downforce: 70, topSpeed: 70, tyreUsage: 70, pitCrewSpeed: 70, ersEfficiency: 70 },
//     },
//     {
//         id: 'rb',
//         name: 'RB',
//         country: 'IT',
//         color: '#6692FF',
//         logo: racingbullsLogo,
//         stats: { pace: 70, reliability: 70, downforce: 70, topSpeed: 70, tyreUsage: 70, pitCrewSpeed: 70, ersEfficiency: 70 },
//     },
//     {
//         id: 'alpine',
//         name: 'Alpine',
//         country: 'FR',
//         color: '#0090FF',
//         logo: alpineLogo,
//         stats: { pace: 70, reliability: 70, downforce: 70, topSpeed: 70, tyreUsage: 70, pitCrewSpeed: 70, ersEfficiency: 70 },
//     },
//     {
//         id: 'haas',
//         name: 'Haas',
//         country: 'US',
//         color: '#B6B6B6',
//         logo: haasLogo,
//         stats: { pace: 70, reliability: 70, downforce: 70, topSpeed: 70, tyreUsage: 70, pitCrewSpeed: 70, ersEfficiency: 70 },
//     },
//     {
//         id: 'audi',
//         name: 'Audi',
//         country: 'DE',
//         color: '#F50537',
//         logo: audiLogo,
//         stats: { pace: 70, reliability: 70, downforce: 70, topSpeed: 70, tyreUsage: 70, pitCrewSpeed: 70, ersEfficiency: 70 },
//     },
//     {
//         id: 'williams',
//         name: 'Williams',
//         country: 'GB',
//         color: '#00A3E0',
//         logo: williamsLogo,
//         stats: { pace: 70, reliability: 70, downforce: 70, topSpeed: 70, tyreUsage: 70, pitCrewSpeed: 70, ersEfficiency: 70 },
//     },
//     {
//         id: 'aston-martin',
//         name: 'Aston Martin',
//         country: 'GB',
//         color: '#006F62',
//         logo: astonMartinLogo,
//         stats: { pace: 70, reliability: 70, downforce: 70, topSpeed: 70, tyreUsage: 70, pitCrewSpeed: 70, ersEfficiency: 70 },
//     },
//     {
//         id: 'cadillac',
//         name: 'Cadillac',
//         country: 'US',
//         color: '#005BAC',
//         logo: cadillacLogo,
//         stats: { pace: 70, reliability: 70, downforce: 70, topSpeed: 70, tyreUsage: 70, pitCrewSpeed: 70, ersEfficiency: 70 },
//     }
// ];
