import type { RaceTimingRow } from "../types/RaceTimingRow";

export const raceTimingMock: RaceTimingRow[] = [
    {
        position: 1,
        number: 81,
        code: "PIA",
        name: "Oscar Piastri",
        country: "AU",
        team: "McLaren",
        tyre: "Medium",
        laps: 23,
        interval: "Leader",
        lastLap: "1:20.512",
        bestLap: "1:20.101",
        ers: 81,
        fuel: 76,
        pitStops: 1
    },
    {
        position: 2,
        number: 4,
        code: "NOR",
        name: "Lando Norris",
        country: "GB",
        team: "McLaren",
        tyre: "Medium",
        laps: 23,
        interval: "+1.247",
        lastLap: "1:20.623",
        bestLap: "1:20.222",
        ers: 74,
        fuel: 75,
        pitStops: 1
    },
    {
        position: 3,
        number: 1,
        code: "VER",
        name: "Max Verstappen",
        country: "NL",
        team: "Red Bull",
        tyre: "Hard",
        laps: 23,
        interval: "+2.823",
        lastLap: "1:20.844",
        bestLap: "1:20.335",
        ers: 62,
        fuel: 71,
        pitStops: 1
    },
    {
        position: 4,
        number: 16,
        code: "LEC",
        name: "Charles Leclerc",
        country: "MC",
        team: "Ferrari",
        tyre: "Hard",
        laps: 23,
        interval: "+4.195",
        lastLap: "1:20.992",
        bestLap: "1:20.611",
        ers: 69,
        fuel: 73,
        pitStops: 1
    },
    {
        position: 5,
        number: 63,
        code: "RUS",
        name: "George Russell",
        country: "GB",
        team: "Mercedes",
        tyre: "Soft",
        laps: 23,
        interval: "+5.743",
        lastLap: "1:21.102",
        bestLap: "1:20.734",
        ers: 51,
        fuel: 70,
        pitStops: 2
    }
];